Aviron moved to 0.16.0
That being said, I'm seeing the following from the build output. It
seems to be a compiler bug:

error: error: Alias and aliasee types don't match (Producer: 'zig 0.16.0' Reader: 'LLVM 21.1.0')